import type { DeviceAdapterCapabilities } from "@/multispecies/adapters/DeviceAdapter";

export type IntegrationAuthType = "oauth" | "api_key" | "webhook_secret" | "csv_import" | "bluetooth" | "gateway" | "none";

export type IntegrationCatalogItem = {
  id: string;
  name: string;
  website?: string;
  status: "mock" | "beta" | "ready" | "planned";
  segment: "pet_health" | "pet_gps" | "farm_health" | "farm_fertility" | "generic";
  auth: IntegrationAuthType[];
  capabilities: Pick<
    DeviceAdapterCapabilities,
    "adapterType" | "brand" | "deviceCategory" | "connectivity" | "speciesSupported" | "supportedMetrics" | "supportedAlerts" | "integrationLevel"
  >;
  notes: string[];
  knownLimits: string[];
  setupChecklist: string[];
};

export const INTEGRATION_CATALOG: IntegrationCatalogItem[] = [
  {
    id: "petpace",
    name: "PetPace",
    status: "planned",
    segment: "pet_health",
    auth: ["api_key", "webhook_secret"],
    capabilities: {
      adapterType: "PetPaceAdapter",
      brand: "PetPace",
      integrationLevel: "planned",
      deviceCategory: "collar",
      connectivity: ["lte"],
      speciesSupported: ["pet"],
      supportedMetrics: ["heart_rate", "respiratory_rate", "body_temperature", "hrv", "activity_score", "resting_state", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["fever", "respiratory_out_of_range", "tachycardia", "device_offline", "battery_low"],
    },
    notes: ["Collare salute: parametri vitali + attività.", "Ottimo per alert sanitari rapidi."],
    knownLimits: ["Disponibilità API/limiti dipendono dal contratto vendor."],
    setupChecklist: ["Abilita accesso API", "Configura endpoint webhook", "Mappa metriche → metricType"],
  },
  {
    id: "tractive",
    name: "Tractive",
    status: "planned",
    segment: "pet_gps",
    auth: ["oauth", "api_key"],
    capabilities: {
      adapterType: "TractiveAdapter",
      brand: "Tractive",
      integrationLevel: "planned",
      deviceCategory: "gps_tracker",
      connectivity: ["lte"],
      speciesSupported: ["pet"],
      supportedMetrics: ["location_lat", "location_lng", "speed", "activity_score", "sleep_duration", "geofence_status", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["geofence_breach", "device_offline", "battery_low"],
    },
    notes: ["GPS live, storico spostamenti, geofence.", "Perfetto per sicurezza e ritrovamento."],
    knownLimits: ["Aggiornamento live dipende dal piano/firmware."],
    setupChecklist: ["OAuth/app registration", "Sincronizzazione posizioni", "Geofence mapping"],
  },
  {
    id: "fi",
    name: "Fi",
    status: "planned",
    segment: "pet_gps",
    auth: ["oauth"],
    capabilities: {
      adapterType: "FiAdapter",
      brand: "Fi",
      integrationLevel: "planned",
      deviceCategory: "collar",
      connectivity: ["lte"],
      speciesSupported: ["pet"],
      supportedMetrics: ["location_lat", "location_lng", "speed", "step_count", "activity_score", "sleep_duration", "geofence_status", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["geofence_breach", "device_offline", "battery_low"],
    },
    notes: ["Collare GPS + attività/steps."],
    knownLimits: ["API pubbliche potrebbero non coprire tutti i dati."],
    setupChecklist: ["OAuth/app registration", "Mapping attività/steps", "Battery/offline rules"],
  },
  {
    id: "whistle",
    name: "Whistle",
    status: "planned",
    segment: "pet_gps",
    auth: ["oauth"],
    capabilities: {
      adapterType: "WhistleAdapter",
      brand: "Whistle",
      integrationLevel: "planned",
      deviceCategory: "gps_tracker",
      connectivity: ["lte"],
      speciesSupported: ["pet"],
      supportedMetrics: ["location_lat", "location_lng", "speed", "activity_score", "sleep_duration", "device_battery_level", "device_online"],
      supportedAlerts: ["geofence_breach", "device_offline", "battery_low"],
    },
    notes: ["GPS + attività (mercato US)."],
    knownLimits: ["Integrazione dipende da disponibilità API."],
    setupChecklist: ["OAuth", "Sync posizioni", "Geofence"],
  },
  {
    id: "garmin",
    name: "Garmin (Pet tracking)",
    status: "planned",
    segment: "pet_gps",
    auth: ["api_key"],
    capabilities: {
      adapterType: "GarminAlphaAdapter",
      brand: "Garmin",
      integrationLevel: "planned",
      deviceCategory: "gps_tracker",
      connectivity: ["satellite", "mixed"],
      speciesSupported: ["pet"],
      supportedMetrics: ["location_lat", "location_lng", "speed", "device_battery_level", "device_online"],
      supportedAlerts: ["geofence_breach", "device_offline", "battery_low"],
    },
    notes: ["Tracking avanzato (anche in aree remote)."],
    knownLimits: ["Forte variabilità per modello/linea prodotto."],
    setupChecklist: ["Definire canale d’integrazione (API/gateway)", "Mapping GPS", "Offline/battery"],
  },
  {
    id: "cowmanager",
    name: "CowManager",
    status: "planned",
    segment: "farm_fertility",
    auth: ["api_key", "webhook_secret"],
    capabilities: {
      adapterType: "CowManagerAdapter",
      brand: "CowManager",
      integrationLevel: "planned",
      deviceCategory: "ear_tag",
      connectivity: ["gateway", "lorawan"],
      speciesSupported: ["livestock"],
      supportedMetrics: ["ear_temperature", "movement_activity", "inactivity_duration", "rumination_duration", "estrus_probability", "insemination_window_score", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["estrus_detected", "rumination_drop", "fever", "device_offline", "battery_low"],
    },
    notes: ["Fertilità + benessere mandria (tag auricolari)."],
    knownLimits: ["Dati e cadenza dipendono dal gateway aziendale."],
    setupChecklist: ["Abilita API/webhook", "Mapping ruminazione/estro", "Regole farm"],
  },
  {
    id: "smaxtec",
    name: "SmaXtec",
    status: "planned",
    segment: "farm_health",
    auth: ["api_key", "webhook_secret"],
    capabilities: {
      adapterType: "SmaxtecAdapter",
      brand: "Smaxtec",
      integrationLevel: "planned",
      deviceCategory: "bolus",
      connectivity: ["gateway"],
      speciesSupported: ["livestock"],
      supportedMetrics: ["inner_body_temperature", "rumination_score", "movement_activity", "illness_risk_score", "ph_value", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["illness_risk", "fever", "device_offline"],
    },
    notes: ["Bolus: temperatura interna, ruminazione, pH."],
    knownLimits: ["Metriche specifiche dipendono dal modello."],
    setupChecklist: ["Abilita API/webhook", "Mapping bolus", "Alert febbre/malessere"],
  },
  {
    id: "sensehub",
    name: "SenseHub",
    status: "planned",
    segment: "farm_fertility",
    auth: ["api_key", "webhook_secret", "gateway"],
    capabilities: {
      adapterType: "SenseHubAdapter",
      brand: "SenseHub",
      integrationLevel: "planned",
      deviceCategory: "collar",
      connectivity: ["gateway"],
      speciesSupported: ["livestock"],
      supportedMetrics: ["activity_score", "rumination_duration", "estrus_probability", "insemination_window_score", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["estrus_detected", "device_offline"],
    },
    notes: ["Collare + gateway: attività/ruminazione/estro."],
    knownLimits: ["Gateway richiesto in molte installazioni."],
    setupChecklist: ["Config gateway", "Mapping metriche", "Regole estro"],
  },
  {
    id: "nedap",
    name: "Nedap CowControl",
    status: "planned",
    segment: "farm_fertility",
    auth: ["api_key", "gateway"],
    capabilities: {
      adapterType: "NedapCowControlAdapter",
      brand: "Nedap",
      integrationLevel: "planned",
      deviceCategory: "collar",
      connectivity: ["gateway"],
      speciesSupported: ["livestock"],
      supportedMetrics: ["activity_score", "rumination_duration", "estrus_probability", "insemination_window_score", "device_online"],
      supportedAlerts: ["estrus_detected", "device_offline"],
    },
    notes: ["Monitoraggio calore/attività con sistemi aziendali."],
    knownLimits: ["Accesso dati spesso tramite integrazione enterprise."],
    setupChecklist: ["Definire canale dati", "Mapping estro", "Alert mandria"],
  },
  {
    id: "generic_gps",
    name: "Generic GPS Collar",
    status: "beta",
    segment: "generic",
    auth: ["webhook_secret"],
    capabilities: {
      adapterType: "GenericGpsCollarAdapter",
      brand: "Generic",
      integrationLevel: "beta",
      deviceCategory: "gps_tracker",
      connectivity: ["lte", "satellite"],
      speciesSupported: ["pet"],
      supportedMetrics: ["location_lat", "location_lng", "speed", "geofence_status", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["geofence_breach", "device_offline", "battery_low"],
    },
    notes: ["Connettore generico via webhook/polling per tracker GPS."],
    knownLimits: ["Serve mapping payload specifico per brand."],
    setupChecklist: ["Definisci mapping key→metric", "Configura secret", "Test ingest"],
  },
  {
    id: "generic_ble",
    name: "Generic Bluetooth Health Tag",
    status: "beta",
    segment: "generic",
    auth: ["bluetooth"],
    capabilities: {
      adapterType: "GenericBluetoothHealthTagAdapter",
      brand: "Generic",
      integrationLevel: "beta",
      deviceCategory: "biometric_sensor",
      connectivity: ["bluetooth"],
      speciesSupported: ["pet"],
      supportedMetrics: ["heart_rate", "respiratory_rate", "body_temperature", "activity_score", "device_battery_level", "device_signal_strength", "device_online"],
      supportedAlerts: ["tachycardia", "fever", "device_offline", "battery_low"],
    },
    notes: ["Bridge BLE → app (modalità futura)."],
    knownLimits: ["Richiede implementazione BLE nativa (Capacitor/Flutter)."],
    setupChecklist: ["Definire protocollo BLE", "Normalizzazione", "Caching offline"],
  },
  {
    id: "manual_farm",
    name: "Manual Farm Sensor",
    status: "beta",
    segment: "generic",
    auth: ["none"],
    capabilities: {
      adapterType: "ManualFarmSensorAdapter",
      brand: "Manual",
      integrationLevel: "beta",
      deviceCategory: "clip",
      connectivity: ["mixed"],
      speciesSupported: ["livestock"],
      supportedMetrics: ["body_temperature", "water_intake", "eating_duration", "rumination_duration", "movement_activity"],
      supportedAlerts: ["manual_flag"],
    },
    notes: ["Inserimento manuale (operatore/consulente) per completare dati mancanti."],
    knownLimits: ["Dipende da disciplina operativa."],
    setupChecklist: ["Definire checklist aziendale", "Soglie per alert manuali"],
  },
];
